language:
  cpp

dist: 
  trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - libassimp-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libopenal-dev
      - libsndfile1-dev
      - libx11-dev
      - libxcb-cursor-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - mesa-common-dev

sudo:
  required

notifications:
  email: true

env:
  - CONFIG=debug
  - CONFIG=release

script:
  - export CC=clang-3.8
  - export CXX=clang++-3.8
  - cd build
  - ./premake5-linux64 --cc=clang gmake
  - cd gmake
  - make -j4 -f NazaraEngine.make config=${CONFIG}dynamic_x64

after_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib/gmake/x64/:../extlibs/lib/gmake/x64/
  - cd ../../tests
  - ./NazaraUnitTests
