language: cpp
sudo: required
services:
  - docker

before_install:
  - docker build -t nazara .

script:
  - docker run -v `pwd`:/NazaraEngine nazara
    sh -c "cd build &&
       ./premake5-linux64 --with-examples gmake &&
       cd gmake &&
       make -j4 -f NazaraEngine.make &&
       cd ../../tests &&
       export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib/gmake/x64/:../extlibs/lib/gmake/x64/
    "

notifications:
  email: true

branches:
  only:
    - master

